name: prettier
on: [push]
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - run: |
          npm install
          npm run prettier-check
